server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
#    url: jdbc:postgresql://ep-bold-base-a10jwdip-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_o7lCOYN1GLqs&sslmode=require&channelBinding=require
    url: jdbc:postgresql://ep-bold-base-a10jwdip-pooler.ap-southeast-1.aws.neon.tech/neondb
    username: neondb_owner
    password: npg_o7lCOYN1GLqs
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate   # hoặc none, create, tùy nhu cầu
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: qlnt

cloudinary:
  cloud-name: dumrmr6xa
  api-key: 712522473725651
  api-secret: HUieNrl24z2j5YkpoBAgbjr1vL4


# Cấu hình CORS cho frontend dev
cors:
  allowed-origins: "http://localhost:3000,http://localhost:4200,http://localhost:5173,https://6p137r5g-5173.asse.devtunnels.ms,https://da-qlnt-fe.vercel.app"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "Authorization,Link,X-Total-Count,X-QuanLyNhaTro-alert,X-QuanLyNhaTro-error,X-QuanLyNhaTro-params"
  allow-credentials: true
  max-age: 1800

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

jwt:
#  signerKey: "4CIrkkE8snlW40XyWBQQiH7Lu9GUsIbZqFSPq5m94xRji99WK5Pc0PfLjMnXcagm"
  signerKey: "edd3553e065fcac9be5328cfe67be0acf1faef71130070e9d3a753cc01441acd"
  valid-duration: 36000 # in seconds
  refreshable-duration: 360000 # in seconds
